<?php
/**
 * Content.
 *
 * @copyright Axel Guckelsberger (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Axel Guckelsberger <vorstand@zikula.de>.
 * @link https://zikula.de
 * @link https://ziku.la
 * @version Generated by ModuleStudio 1.3.2 (https://modulestudio.de).
 */

namespace Zikula\ContentModule\Form\EventListener;

use Zikula\ContentModule\Form\EventListener\Base\AbstractTranslationListener;

/**
 * Translation listener implementation class.
 */
class TranslationListener extends AbstractTranslationListener
{
    // feel free to add your customisation here
}
