<?php
/**
 * Content.
 *
 * @copyright Axel Guckelsberger (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Axel Guckelsberger <info@ziku.la>.
 * @link https://ziku.la
 * @version Generated by ModuleStudio 1.3.2 (https://modulestudio.de).
 */

namespace Zikula\ContentModule\ContentType;

use Symfony\Component\HttpFoundation\RequestStack;
use Zikula\Common\Content\AbstractContentType;
use Zikula\Common\Content\ContentTypeInterface;
use Zikula\ContentModule\ContentType\Form\Type\GoogleMapType as FormType;

/**
 * Google map content type.
 */
class GoogleMapType extends AbstractContentType
{
    /**
     * @var RequestStack
     */
    protected $requestStack;

    /**
     * @var string
     */
    protected $googleMapsApiKey;

    /**
     * @inheritDoc
     */
    public function getCategory()
    {
        return ContentTypeInterface::CATEGORY_EXTERNAL;
    }

    /**
     * @inheritDoc
     */
    public function getIcon()
    {
        return 'map-marker';
    }

    /**
     * @inheritDoc
     */
    public function getTitle()
    {
        return $this->__('Google map');
    }

    /**
     * @inheritDoc
     */
    public function getDescription()
    {
        return $this->__('Display a Google map position.');
    }

    /**
     * @inheritDoc
     */
    public function getAdminInfo()
    {
        return $this->__('You need to specify a Google Maps API key in the configuration form in order to activate this plugin.');
    }

    /**
     * @inheritDoc
     */
    public function isActive()
    {
        // Only active when the API key is available
        return '' != $this->googleMapsApiKey && parent::isActive();
    }

    /**
     * @inheritDoc
     */
    public function getDefaultData()
    {
        return [
            'latitude' => '55.8756960390043',
            'longitude' => '12.36185073852539',
            'zoom' => 5,
            'mapType' => 'roadmap',
            'height' => 400,
            'text' => '',
            'infoText' => '',
            'trafficOverlay' => false,
            'bicycleOverlay' => false,
            'streetViewControl' => false,
            'directionsLink' => false,
            'directionsInline' => false
        ];
    }

    /**
     * @inheritDoc
     */
    public function getTranslatableDataFields()
    {
        return ['text', 'infoText'];
    }

    /**
     * @inheritDoc
     */
    public function getSearchableText()
    {
        return html_entity_decode(strip_tags($this->data['text']));
    }

    /**
     * @inheritDoc
     */
    public function getEditFormClass()
    {
        return FormType::class;
    }

    /**
     * @inheritDoc
     */
    public function getAssets($context)
    {
        $locale = $this->requestStack->getMasterRequest()->getLocale();

        $assets = parent::getAssets($context);

        if (ContentTypeInterface::CONTEXT_VIEW == $context) {
            $assets['js'][] = $this->assetHelper->resolve('@ZikulaContentModule:js/ZikulaContentModule.ContentType.GoogleMap.js');
        }
        if (ContentTypeInterface::CONTEXT_EDIT == $context) {
            $assets['js'][] = $this->assetHelper->resolve('@ZikulaContentModule:js/ZikulaContentModule.ContentType.GoogleEdit.js');
        }

        $googleMapsScript = 'https://maps.google.com/maps/api/js?v=3&key=' . $this->googleMapsApiKey . '&language=' . $locale;
        if (ContentTypeInterface::CONTEXT_VIEW == $context) {
            $googleMapsScript .= '&callback=contentInitGoogleMapDisplay';
        }
        if (ContentTypeInterface::CONTEXT_EDIT == $context) {
            $googleMapsScript .= '&callback=contentInitGoogleMapEdit';
        }
        $assets['js'][] = $googleMapsScript;

        return $assets;
    }

    /**
     * @inheritDoc
     */
    public function getJsEntrypoint($context)
    {
        /*if (ContentTypeInterface::CONTEXT_VIEW == $context) {
            return 'contentInitGoogleMapDisplay';
        }*/
        if (ContentTypeInterface::CONTEXT_EDIT == $context) {
            return 'contentInitGoogleMapEdit';
        }

        return null;
    }

    /**
     * @param RequestStack $requestStack
     */
    public function setRequestStack(RequestStack $requestStack)
    {
        $this->requestStack = $requestStack;
    }

    /**
     * @param string $googleMapsApiKey
     */
    public function setGoogleMapsApiKey($googleMapsApiKey)
    {
        $this->googleMapsApiKey = $googleMapsApiKey;
    }
}
