<?php
/**
 * Content.
 *
 * @copyright Axel Guckelsberger (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Axel Guckelsberger <info@ziku.la>.
 * @link https://ziku.la
 * @version Generated by ModuleStudio 1.3.2 (https://modulestudio.de).
 */

namespace Zikula\ContentModule\ContentType;

use \Twig_Environment;
use Symfony\Bundle\TwigBundle\Loader\FilesystemLoader;
use Zikula\Common\Translator\TranslatorInterface;
use Zikula\ContentModule\AbstractContentType;
use Zikula\ContentModule\ContentTypeInterface;
use Zikula\ContentModule\ContentType\Form\Type\YouTubeType as FormType;
use Zikula\ContentModule\Helper\CacheHelper;
use Zikula\ContentModule\Helper\PermissionHelper;
use Zikula\ThemeModule\Engine\Asset;

/**
 * YouTube content type.
 */
class YouTubeType extends AbstractContentType
{
    /**
     * @var CacheHelper
     */
    protected $cacheHelper;

    /**
     * YouTubeType constructor.
     *
     * @param TranslatorInterface $translator       Translator service instance
     * @param Twig_Environment    $twig             Twig service instance
     * @param FilesystemLoader    $twigLoader       Twig loader service instance
     * @param PermissionHelper    $permissionHelper PermissionHelper service instance
     * @param Asset               $assetHelper      Asset service instance
     * @param CacheHelper         $cacheHelper      CacheHelper service instance
     */
    public function __construct(
        TranslatorInterface $translator,
        Twig_Environment $twig,
        FilesystemLoader $twigLoader,
        PermissionHelper $permissionHelper,
        Asset $assetHelper,
        CacheHelper $cacheHelper
    ) {
        $this->cacheHelper = $cacheHelper;
        parent::__construct($translator, $twig, $twigLoader, $permissionHelper, $assetHelper);
    }

    /**
     * @inheritDoc
     */
    public function getCategory()
    {
        return ContentTypeInterface::CATEGORY_EXTERNAL;
    }

    /**
     * @inheritDoc
     */
    public function getIcon()
    {
        return 'youtube';
    }

    /**
     * @inheritDoc
     */
    public function getTitle()
    {
        return $this->__('YouTube video');
    }

    /**
     * @inheritDoc
     */
    public function getDescription()
    {
        return $this->__('Display a YouTube video clip.');
    }

    /**
     * @inheritDoc
     */
    public function isTranslatable()
    {
        return true;
    }

    /**
     * @inheritDoc
     */
    public function getDefaultData()
    {
        return [
            'url' => '',
            'text' => '',
            'videoId' => '',
            'displayMode' => 'inline',
            'showRelated' => false,
            'autoplay' => false
        ];
    }

    /**
     * @inheritDoc
     */
    public function getSearchableText()
    {
        return html_entity_decode(strip_tags($this->data['text']));
    }

    /**
     * @inheritDoc
     */
    public function displayView()
    {
        $this->data['videoId'] = '';
        $r = '/\?v=([-a-zA-Z0-9_]+)(&|$)/';
        if (preg_match($r, $this->data['url'], $matches)) {
            $this->data['videoId'] = $matches[1];
            // @todo fetch additional data if needed - requires an API key though
            // https://developers.google.com/youtube/v3/docs/
            /*$content = $this->cacheHelper->fetch('someurl' . $this->data['videoId'] . '.php');
            if (false !== $content) {
                $this->data['details'] = @json_decode($content, true);
            }*/
        }

        return parent::displayView();
    }

    /**
     * @inheritDoc
     */
    public function getEditFormClass()
    {
        return FormType::class;
    }
}
