<?php
/**
 * Content.
 *
 * @copyright Axel Guckelsberger (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Axel Guckelsberger <vorstand@zikula.de>.
 * @link https://zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.3.1 (https://modulestudio.de).
 */

namespace Zikula\ContentModule\Form\Type\QuickNavigation;

use Zikula\ContentModule\Form\Type\QuickNavigation\Base\AbstractPageQuickNavType;

/**
 * Page quick navigation form type implementation class.
 */
class PageQuickNavType extends AbstractPageQuickNavType
{
    // feel free to extend the base form type class here
}
