<?php
/**
 * Content.
 *
 * @copyright Axel Guckelsberger (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Axel Guckelsberger <vorstand@zikula.de>.
 * @link https://zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.3.1 (https://modulestudio.de).
 */

namespace Zikula\ContentModule\Entity\Factory;

use Zikula\ContentModule\Entity\Factory\Base\AbstractEntityFactory;

/**
 * Factory class used to create entities and receive entity repositories.
 */
class EntityFactory extends AbstractEntityFactory
{
    // feel free to customise the factory
}
