<?php
/**
 * Content.
 *
 * @copyright Axel Guckelsberger (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Axel Guckelsberger <info@ziku.la>.
 * @link https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

namespace Zikula\ContentModule\HookSubscriber;

use Zikula\ContentModule\HookSubscriber\Base\AbstractPageUiHooksSubscriber;

/**
 * Implementation class for ui hooks subscriber.
 */
class PageUiHooksSubscriber extends AbstractPageUiHooksSubscriber
{
    // feel free to add your own convenience methods here
}
