<?php
/**
 * Content.
 *
 * @copyright Axel Guckelsberger (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Axel Guckelsberger <info@ziku.la>.
 * @link https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

namespace Zikula\ContentModule\Block;

use Zikula\ContentModule\Block\Base\AbstractItemBlock;

/**
 * Generic item detail block implementation class.
 */
class ItemBlock extends AbstractItemBlock
{
    // feel free to extend the item detail block here
}
