<?php
/**
 * Content.
 *
 * @copyright Axel Guckelsberger (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Axel Guckelsberger <info@ziku.la>.
 * @link https://ziku.la
 * @version Generated by ModuleStudio 1.3.2 (https://modulestudio.de).
 */

namespace Zikula\ContentModule\Routing;

use Symfony\Component\Config\Loader\Loader;
use Symfony\Component\Routing\Route;
use Symfony\Component\Routing\RouteCollection;
use Zikula\ExtensionsModule\Api\ApiInterface\VariableApiInterface;

class DynamicRouteLoader extends Loader
{
    /**
     * @var VariableApiInterface
     */
    protected $variableApi;

    /**
     * @var boolean
     */
    protected $isLoaded;

    /**
     * DynamicRouteLoader constructor.
     *
     * @param VariableApiInterface $variableApi VariableApi service instance
     */
    public function __construct(
        VariableApiInterface $variableApi
    ) {
        $this->variableApi = $variableApi;
        $this->isLoaded = false;
    }

    /**
     * @inheritDoc
     */
    public function load($resource, $type = null)
    {
        if (true === $this->isLoaded) {
            throw new \RuntimeException('Do not add the "content_dynamic" loader twice');
        }

        $ignoreBundleName = (bool) $this->variableApi->get('ZikulaContentModule', 'ignoreBundleNameInRoutes', true);
        $ignoreEntityName = (bool) $this->variableApi->get('ZikulaContentModule', 'ignoreEntityNameInRoutes', true);
        $ignoreFirstTreeLevel = (bool) $this->variableApi->get('ZikulaContentModule', 'ignoreFirstTreeLevelInRoutes', true);

        $routeVariants = [
            'admin' => ['pathPrefix' => '/admin', 'controller' => 'adminDisplay'],
            'user' => ['pathPrefix' => '', 'controller' => 'display']
        ];
        $entityPathSegment = true === $ignoreEntityName ? '' : '/page';
        // TODO $ignoreFirstTreeLevel needs to be considered

        $routes = new RouteCollection();

        foreach ($routeVariants as $variantName => $variantData) {
            $path = $variantData['pathPrefix'] . $entityPathSegment . '/{slug}.{_format}';

            $defaults = [
                '_controller' => 'ZikulaContentModule:Page:' . $variantData['controller'],
                '_format' => 'html'
            ];
            $requirements = [
                'slug' => '[^.]+',
                '_format' => 'html|xml|json|ics|pdf'
            ];
            $options = [
                'i18n' => true, // needs to be enabled for locale prefix, BUT we need to remove zikulacontentmodule_page_admindisplay and zikulacontentmodule_page_display from routes.en.po to allow dynamic changes of the corresponding pathes
                'expose' => true,
                'zkPosition' => 'bottom'
            ];
            if (true === $ignoreBundleName) {
                $options['zkNoBundlePrefix'] = true;
            }
            $host = '';
            $schemes = [];
            $methods = ['GET'];
            $condition = ''; // see https://symfony.com/doc/current/routing/conditions.html
            $route = new Route($path, $defaults, $requirements, $options, $host, $schemes, $methods, $condition);

            $routes->add($variantName . 'Display', $route);
        }

        $this->isLoaded = true;

        return $routes;
    }

    /**
     * @inheritDoc
     */
    public function supports($resource, $type = null)
    {
        return 'content_dynamic' === $type;
    }
}
