<?php
/**
 * Content.
 *
 * @copyright Axel Guckelsberger (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Axel Guckelsberger <info@ziku.la>.
 * @link https://zikula.de
 * @link https://ziku.la
 * @version Generated by ModuleStudio 1.3.2 (https://modulestudio.de).
 */

namespace Zikula\ContentModule\Form\Type\Finder;

use Zikula\ContentModule\Form\Type\Finder\Base\AbstractPageFinderType;

/**
 * Page finder form type implementation class.
 */
class PageFinderType extends AbstractPageFinderType
{
    // feel free to extend the base form type class here
}
