<?php

/**
 * Content.
 *
 * @copyright Axel Guckelsberger (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Axel Guckelsberger <info@ziku.la>.
 * @see https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

declare(strict_types=1);

namespace Zikula\ContentModule\Helper;

use Zikula\ContentModule\Helper\Base\AbstractHookHelper;

/**
 * Helper implementation class for hook related methods.
 */
class HookHelper extends AbstractHookHelper
{
    // feel free to add your own convenience methods here
}
