<?php
/**
 * Content.
 *
 * @copyright Axel Guckelsberger (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Axel Guckelsberger <vorstand@zikula.de>.
 * @link https://zikula.de
 * @link https://ziku.la
 * @version Generated by ModuleStudio 1.3.2 (https://modulestudio.de).
 */

namespace Zikula\ContentModule\Listener;

use Zikula\ContentModule\Listener\Base\AbstractGroupListener;

/**
 * Event handler implementation class for group-related events.
 */
class GroupListener extends AbstractGroupListener
{
    // feel free to enhance the parent methods
}
