<?php

declare(strict_types=1);

/**
 * Content.
 *
 * @copyright Axel Guckelsberger (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Axel Guckelsberger <info@ziku.la>.
 * @link https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

namespace Zikula\ContentModule\Listener;

use Zikula\ContentModule\Listener\Base\AbstractUserListener;

/**
 * Event handler implementation class for user-related events.
 */
class UserListener extends AbstractUserListener
{
    // feel free to enhance the parent methods
}
