services:
    # Form field types
    
    zikula_content_module.form.type.field.array:
        class: Zikula\ContentModule\Form\Type\Field\ArrayType
        tags: ['form.type']
    
    zikula_content_module.form.type.field.multilist:
        class: Zikula\ContentModule\Form\Type\Field\MultiListType
        arguments:
            - "@zikula_content_module.listentries_helper"
        tags: ['form.type']
    
    zikula_content_module.form.type.field.translation:
        class: Zikula\ContentModule\Form\Type\Field\TranslationType
        tags: ['form.type']
    
    zikula_content_module.form.type.field.entitytree:
        class: Zikula\ContentModule\Form\Type\Field\EntityTreeType
        arguments:
            - "@zikula_content_module.entity_display_helper"
        tags: ['form.type']
