services:
    zikula_content_module.hook_subscriber.filter_hooks.pages:
        class: Zikula\ContentModule\HookSubscriber\PageFilterHooksSubscriber
        arguments:
            - "@translator.default"
        tags:
            - { name: zikula.hook_subscriber, areaName: 'subscriber.zikulacontentmodule.filter_hooks.pages' }

    zikula_content_module.hook_subscriber.form_aware_hook.pages:
        class: Zikula\ContentModule\HookSubscriber\PageFormAwareHookSubscriber
        arguments:
            - "@translator.default"
        tags:
            - { name: zikula.hook_subscriber, areaName: 'subscriber.zikulacontentmodule.form_aware_hook.pages' }

    zikula_content_module.hook_subscriber.ui_hooks.pages:
        class: Zikula\ContentModule\HookSubscriber\PageUiHooksSubscriber
        arguments:
            - "@translator.default"
        tags:
            - { name: zikula.hook_subscriber, areaName: 'subscriber.zikulacontentmodule.ui_hooks.pages' }

    zikula_content_module.hook_subscriber.filter_hooks.contentitems:
        class: Zikula\ContentModule\HookSubscriber\ContentItemFilterHooksSubscriber
        arguments:
            - "@translator.default"
        tags:
            - { name: zikula.hook_subscriber, areaName: 'subscriber.zikulacontentmodule.filter_hooks.contentitems' }

