services:
    zikula_content_module.multihook_needle.page:
        class: Zikula\ContentModule\Needle\PageNeedle
        arguments:
            - '@translator.default'
            - '@router'
            - '@zikula_content_module.permission_helper'
            - '@zikula_content_module.entity_factory'
            - '@zikula_content_module.entity_display_helper'
        tags: ['zikula.multihook_needle']
